// <auto-generated />
using CarDealershipWebApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CarDealershipWebApplication.Migrations
{
    [DbContext(typeof(CarDealershipWebApplicationContext))]
    [Migration("20180322173727_Initialfix")]
    partial class Initialfix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarDealershipWebApplication.Models.CarMark", b =>
                {
                    b.Property<int>("CarMarkID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MarkName");

                    b.HasKey("CarMarkID");

                    b.ToTable("CarMark");
                });

            modelBuilder.Entity("CarDealershipWebApplication.Models.SparePart", b =>
                {
                    b.Property<int>("SparePartID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CarMarkID");

                    b.Property<int>("SparePartCode");

                    b.Property<string>("SparePartName");

                    b.HasKey("SparePartID");

                    b.HasIndex("CarMarkID");

                    b.ToTable("SparePart");
                });

            modelBuilder.Entity("CarDealershipWebApplication.Models.SparePart", b =>
                {
                    b.HasOne("CarDealershipWebApplication.Models.CarMark", "CarMark")
                        .WithMany()
                        .HasForeignKey("CarMarkID");
                });
#pragma warning restore 612, 618
        }
    }
}
